COCOTB=/home/jdawson/cocotb

VERILOG_SOURCES=top.v rmii_mii.v sgmii.v encode_8b10b.v decode_8b10b.v 
TOPLEVEL=top
MODULE=test_my_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
